image: Visual Studio 2017
clone_folder: c:\projects\FEMM

install:
  - cinst cmake ninja
  - SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - cd c:\projects\FEMM
  - mkdir build_release && cd build_release
  - cmake -A "Win32" ..
  - cd ..

build_script:
  - cd build_release && cmake --build . --config Release --parallel 8 && cd ..
